export function setupZipBtn() {
    const handler = () => downloadZip();
    document.getElementById('downloadZipBtn').addEventListener('click', handler);
    document.getElementById('downloadZipBtn2').addEventListener('click', handler);
}

async function downloadZip() {
    const JSZip = window.JSZip;
    if (!JSZip) { alert('JSZip library not loaded.'); return; }

    const projectName = document.getElementById('projectName').value || 'Project';
    const material = document.getElementById('materialName').value || 'Material';
    const brand = document.getElementById('brandName').value || 'Brand';
    const folderName = `${projectName} — ${material} - ${brand}`.replace(/[<>:"\/\\|?*]/g, '-');

    const items = Array.from(document.querySelectorAll('.index-item-row .index-item-desc'))
        .map(el => el.value.trim()).filter(Boolean);

    if (items.length === 0) { alert('Please add at least one item to the index first.'); return; }

    const zip = new JSZip();
    const root = zip.folder(folderName);

    items.forEach((item, i) => {
        const subName = `${String(i + 1).padStart(2, '0')}. ${item}`.replace(/[<>:"\/\\|?*]/g, '-');
        root.folder(subName);
    });

    root.file('_README.txt', `Submittal Folder: ${folderName}\nGenerated: ${new Date().toLocaleString()}\nGenerated by: BMTC Submittal Generator\n\nFolders:\n${items.map((it, i) => `  ${String(i + 1).padStart(2, '0')}. ${it}`).join('\n')}`);

    const blob = await zip.generateAsync({ type: 'blob' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${folderName}.zip`;
    a.click();
    URL.revokeObjectURL(a.href);
}
